In [1]:
import pandas as pd
import numpy as np
import my_def

<h1>데이터확인 및 가공</h1>
업종명 분류 -> 9개의 중분류로 구분

In [2]:
df = pd.read_csv('Merged_Sales_data_v2.6(selected_store).csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335256 entries, 0 to 335255
Data columns (total 13 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   년분기        335256 non-null  int64
 1   행정동        335256 non-null  object
 2   업종명        335256 non-null  object
 3   월매출(점포)    335256 non-null  int64
 4   인구수        335256 non-null  int64
 5   지역생활인구     335256 non-null  int64
 6   장기외국인      335256 non-null  int64
 7   단기외국인      335256 non-null  int64
 8   주차장면적(면)   335256 non-null  int64
 9   주차장개수(개소)  335256 non-null  int64
 10  학교수        335256 non-null  int64
 11  학생수        335256 non-null  int64
 12  버스정류장수     335256 non-null  int64
dtypes: int64(11), object(2)
memory usage: 33.3+ MB

In [4]:
categories = {
    "식음료": [
        "커피-음료", "패스트푸드점", "분식전문점", "한식음식점",
        "양식음식점", "일식음식점", "호프-간이주점", "제과점", "중식음식점"
    ],
    "의료_건강": [
        "의약품", "치과의원", "일반의원", "한의원", "피부관리실", "의료기기"
    ],
    "소매_편의": [
        "미곡판매", "편의점", "슈퍼마켓", "반찬가게", "육류판매",
        "수산물판매", "문구", "청과상"
    ],
    "미용_패션": [
        "미용실", "화장품", "네일숍", "신발", "일반의류"
    ],
    "교육_학원": [
        "스포츠 강습", "예술학원", "외국어학원"
    ],
    "취미_레저": [
        "스포츠클럽", "골프연습장", "완구", "당구장", "노래방",
        "운동/경기용품", "자전거 및 기타운송장비", "서적"
    ],
    "생활서비스": [
        "세탁소", "철물점", "안경", "인테리어", "자동차미용", "자동차수리",
        "가전제품수리", "조명용품", "섬유제품", "전자상거래업"
    ],
    "가구_전자기기": [
        "가구", "가전제품", "핸드폰", "시계및귀금속", "컴퓨터및주변장치판매", "가방"
    ],
    "부동산_숙박": [
        "부동산중개업", "고시원"
    ]
}

In [5]:
def categorize_merged_data(merged_data):
    for category, biz_list in categories.items():
        if merged_data in biz_list:
            return category
    return "기타"

In [6]:
df['업종별카테고리'] = df['업종명'].apply(categorize_merged_data)
df.head(1)

,년분기,행정동,업종명,월매출(점포),인구수,지역생활인구,장기외국인,단기외국인,주차장면적(면),주차장개수(개소),학교수,학생수,버스정류장수,업종별카테고리
0,20191,가락1동,미곡판매,2796909658,20186,523724,13892,1772,20942,83,3,1586,14,소매_편의

In [7]:
grouped_df = df.groupby(['년분기', '행정동', '업종별카테고리']).agg({
    '월매출(점포)': 'sum',
    # '주중매출': 'sum',
    # '주말매출': 'sum',
    # '점포수': 'sum',
    '인구수' : 'mean',
    '지역생활인구': 'mean',
    '장기외국인': 'mean',
    '단기외국인': 'mean',
    '주차장면적(면)': 'mean',
    '주차장개수(개소)': 'mean',
    '학교수': 'mean',
    '학생수': 'mean',
    '버스정류장수': 'mean'	
}).reset_index()

grouped_df

,년분기,행정동,업종별카테고리,월매출(점포),인구수,지역생활인구,장기외국인,단기외국인,주차장면적(면),주차장개수(개소),학교수,학생수,버스정류장수
0,20191,가락1동,생활서비스,3975118,20186.0,523724.0,13892.0,1772.0,20942.0,83.0,3.0,1586.0,14.0
1,20191,가락1동,소매_편의,6565196464,20186.0,523724.0,13892.0,1772.0,20942.0,83.0,3.0,1586.0,14.0
2,20191,가락1동,식음료,404795979,20186.0,523724.0,13892.0,1772.0,20942.0,83.0,3.0,1586.0,14.0
3,20191,가락1동,의료_건강,170057995,20186.0,523724.0,13892.0,1772.0,20942.0,83.0,3.0,1586.0,14.0
4,20191,가락2동,가구_전자기기,10626421,34155.0,722081.0,8185.0,1925.0,14340.0,1058.0,2.0,1867.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72365,20242,흑석동,생활서비스,52455262,32491.0,848734.0,77201.0,6202.0,16937.0,298.0,0.0,0.0,59.0
72366,20242,흑석동,소매_편의,460400862,32491.0,848734.0,77201.0,6202.0,16937.0,298.0,0.0,0.0,59.0
72367,20242,흑석동,식음료,331108691,32491.0,848734.0,77201.0,6202.0,16937.0,298.0,0.0,0.0,59.0
72368,20242,흑석동,의료_건강,963794015,32491.0,848734.0,77201.0,6202.0,16937.0,298.0,0.0,0.0,59.0
72369,20242,흑석동,취미_레저,24619516,32491.0,848734.0,77201.0,6202.0,16937.0,298.0,0.0,0.0,59.0

In [8]:
grouped_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72370 entries, 0 to 72369
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   년분기        72370 non-null  int64
 1   행정동        72370 non-null  object
 2   업종별카테고리    72370 non-null  object
 3   월매출(점포)    72370 non-null  int64
 4   인구수        72370 non-null  float64
 5   지역생활인구     72370 non-null  float64
 6   장기외국인      72370 non-null  float64
 7   단기외국인      72370 non-null  float64
 8   주차장면적(면)   72370 non-null  float64
 9   주차장개수(개소)  72370 non-null  float64
 10  학교수        72370 non-null  float64
 11  학생수        72370 non-null  float64
 12  버스정류장수     72370 non-null  float64
dtypes: float64(9), int64(2), object(2)
memory usage: 7.2+ MB

In [9]:
grouped_df = my_def.reduce_memory_usage(grouped_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72370 entries, 0 to 72369
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   년분기        72370 non-null  int16
 1   행정동        72370 non-null  object
 2   업종별카테고리    72370 non-null  object
 3   월매출(점포)    72370 non-null  int64
 4   인구수        72370 non-null  float16
 5   지역생활인구     72370 non-null  float32
 6   장기외국인      72370 non-null  float32
 7   단기외국인      72370 non-null  float32
 8   주차장면적(면)   72370 non-null  float32
 9   주차장개수(개소)  72370 non-null  float16
 10  학교수        72370 non-null  float16
 11  학생수        72370 non-null  float16
 12  버스정류장수     72370 non-null  float16
dtypes: float16(5), float32(4), int16(1), int64(1), object(2)
memory usage: 3.6+ MB
None

In [10]:
df = grouped_df
df[df["업종별카테고리"] == "기타"]

c:\Dev\Python\Python313\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

Empty DataFrame
Columns: [년분기, 행정동, 업종별카테고리, 월매출(점포), 인구수, 지역생활인구, 장기외국인, 단기외국인, 주차장면적(면), 주차장개수(개소), 학교수, 학생수, 버스정류장수]
Index: []

<h1>전체업종 선형회귀 분석</h1>

In [11]:
df[df["업종별카테고리"] == "기타"]

Empty DataFrame
Columns: [년분기, 행정동, 업종별카테고리, 월매출(점포), 인구수, 지역생활인구, 장기외국인, 단기외국인, 주차장면적(면), 주차장개수(개소), 학교수, 학생수, 버스정류장수]
Index: []

In [12]:
df = my_def.reduce_memory_usage(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72370 entries, 0 to 72369
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   년분기        72370 non-null  int16
 1   행정동        72370 non-null  object
 2   업종별카테고리    72370 non-null  object
 3   월매출(점포)    72370 non-null  int64
 4   인구수        72370 non-null  float16
 5   지역생활인구     72370 non-null  float32
 6   장기외국인      72370 non-null  float32
 7   단기외국인      72370 non-null  float32
 8   주차장면적(면)   72370 non-null  float32
 9   주차장개수(개소)  72370 non-null  float16
 10  학교수        72370 non-null  float16
 11  학생수        72370 non-null  float16
 12  버스정류장수     72370 non-null  float16
dtypes: float16(5), float32(4), int16(1), int64(1), object(2)
memory usage: 3.6+ MB
None

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# '행정동'과 '업종별카테고리' 컬럼 원핫인코딩 수행
df2 = pd.get_dummies(df, columns=['행정동', '업종별카테고리'], drop_first=True)

# 피처와 타겟 설정
features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df2.columns if col.startswith('행정동_') or col.startswith('업종별카테고리_')]
target = '월매출(점포)'

X = df2[features]
y = df2[target]

# 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 랜덤 포레스트 모델 학습
model = RandomForestRegressor(random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

# 피처 셀렉션 적용 여부
feature_selection = True  # 피처 셀렉션 적용 여부 설정
importance_threshold = 0.01  # 중요도 임계값 설정
if feature_selection:
    # 피처 중요도 추출
    feature_importances = model.feature_importances_
    feature_importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances})
    feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

    # 중요도 임계값 이하의 피처 제거 (행정동 및 업종별카테고리 제외)
    selected_features_df = feature_importance_df[(feature_importance_df['Importance'] > importance_threshold) & (~feature_importance_df['Feature'].str.startswith('행정동_')) & (~feature_importance_df['Feature'].str.startswith('업종별카테고리_'))]
    selected_features = selected_features_df['Feature']

    # 선택된 피처들로 새로운 데이터셋 생성
    X_train = X_train[selected_features]
    X_test = X_test[selected_features]

    print("Selected Features after Feature Selection (sorted by importance):")
    print(selected_features_df.to_string(index=False))

    # 모델 재학습
    model.fit(X_train, y_train)

# 모델 정보 출력
print(f"Model: {model}")

Selected Features after Feature Selection (sorted by importance):
  Feature  Importance
   버스정류장수    0.055936
   지역생활인구    0.039988
주차장개수(개소)    0.032870
    장기외국인    0.029030
 주차장면적(면)    0.027366
      인구수    0.026634
      년분기    0.021190
      학생수    0.020874
    단기외국인    0.015203
Model: RandomForestRegressor(n_jobs=-1, random_state=42)

In [20]:
selected_features_df.reset_index(drop=True)

     Feature  Importance
0     버스정류장수    0.055936
1     지역생활인구    0.039988
2  주차장개수(개소)    0.032870
3      장기외국인    0.029030
4   주차장면적(면)    0.027366
5        인구수    0.026634
6        년분기    0.021190
7        학생수    0.020874
8      단기외국인    0.015203

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# 데이터프레임(df) 제공 필요
# 예: df = pd.read_csv('your_file.csv')

# '행정동'과 '업종별카테고리' 컬럼 원핫인코딩 수행
df2 = pd.get_dummies(df, columns=['행정동', '업종별카테고리'], drop_first=True)

# 피처와 타겟 설정
features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df2.columns if col.startswith('행정동_') or col.startswith('업종별카테고리_')]
target = '월매출(점포)'

X = df2[features]
y = df2[target]

# 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 랜덤 포레스트 모델 학습 및 예측
model = RandomForestRegressor(random_state=42, n_jobs=-1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# 모델 평가 호출
evaluation_results = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)

# 결과 출력
evaluation_results

{'Model': 'RandomForestRegressor',
 'Scaler': 'None',
 'train_mse': np.float64(680710846649535.1),
 'test_mse': np.float64(3912119466242086.0),
 'train_rmse': np.float64(26090435.92),
 'test_rmse': np.float64(62546938.1),
 'train_r2': 0.99,
 'test_r2': 0.95,
 'train_mae': np.float64(11292838.94),
 'test_mae': np.float64(29019445.18),
 'train_mae_ratio': np.float64(5.26),
 'test_mae_ratio': np.float64(13.85)}

단기외국인 삭제

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# 데이터프레임(df) 제공 필요
# 예: df = pd.read_csv('your_file.csv')

# '행정동'과 '업종별카테고리' 컬럼 원핫인코딩 수행
df2 = pd.get_dummies(df, columns=['행정동', '업종별카테고리'], drop_first=True)

# 피처와 타겟 설정
features = ['년분기', '인구수', '지역생활인구', '장기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df2.columns if col.startswith('행정동_') or col.startswith('업종별카테고리_')]
target = '월매출(점포)'

X = df2[features]
y = df2[target]

# 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 랜덤 포레스트 모델 학습 및 예측
model = RandomForestRegressor(random_state=42, n_jobs=-1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# 모델 평가 호출
evaluation_results2 = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)

# 결과 출력
evaluation_results2

{'Model': 'RandomForestRegressor',
 'Scaler': 'None',
 'train_mse': np.float64(669608262830991.1),
 'test_mse': np.float64(3686517625622915.0),
 'train_rmse': np.float64(25876790.04),
 'test_rmse': np.float64(60716699.73),
 'train_r2': 0.99,
 'test_r2': 0.95,
 'train_mae': np.float64(11015518.93),
 'test_mae': np.float64(28199150.24),
 'train_mae_ratio': np.float64(5.13),
 'test_mae_ratio': np.float64(13.46)}

학생수 삭제

In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# 데이터프레임(df) 제공 필요
# 예: df = pd.read_csv('your_file.csv')

# '행정동'과 '업종별카테고리' 컬럼 원핫인코딩 수행
df2 = pd.get_dummies(df, columns=['행정동', '업종별카테고리'], drop_first=True)

# 피처와 타겟 설정
features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '버스정류장수'] + [col for col in df2.columns if col.startswith('행정동_') or col.startswith('업종별카테고리_')]
target = '월매출(점포)'

X = df2[features]
y = df2[target]

# 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 랜덤 포레스트 모델 학습 및 예측
model = RandomForestRegressor(random_state=42, n_jobs=-1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# 모델 평가 호출
evaluation_results3 = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)

# 결과 출력
evaluation_results3

{'Model': 'RandomForestRegressor',
 'Scaler': 'None',
 'train_mse': np.float64(669045452360934.1),
 'test_mse': np.float64(3826396492209327.5),
 'train_rmse': np.float64(25865912.94),
 'test_rmse': np.float64(61857873.32),
 'train_r2': 0.99,
 'test_r2': 0.95,
 'train_mae': np.float64(11102428.65),
 'test_mae': np.float64(28524090.94),
 'train_mae_ratio': np.float64(5.17),
 'test_mae_ratio': np.float64(13.62)}

단기외국인 학생수 삭제

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# 데이터프레임(df) 제공 필요
# 예: df = pd.read_csv('your_file.csv')

# '행정동'과 '업종별카테고리' 컬럼 원핫인코딩 수행
df2 = pd.get_dummies(df, columns=['행정동', '업종별카테고리'], drop_first=True)

# 피처와 타겟 설정
features = ['년분기', '인구수', '지역생활인구', '장기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '버스정류장수'] + [col for col in df2.columns if col.startswith('행정동_') or col.startswith('업종별카테고리_')]
target = '월매출(점포)'

X = df2[features]
y = df2[target]

# 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 랜덤 포레스트 모델 학습 및 예측
model = RandomForestRegressor(random_state=42, n_jobs=-1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# 모델 평가 호출
evaluation_results4 = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)

# 결과 출력
evaluation_results4

{'Model': 'RandomForestRegressor',
 'Scaler': 'None',
 'train_mse': np.float64(665447721270874.6),
 'test_mse': np.float64(3562206719830102.0),
 'train_rmse': np.float64(25796273.4),
 'test_rmse': np.float64(59684225.05),
 'train_r2': 0.99,
 'test_r2': 0.95,
 'train_mae': np.float64(10811519.62),
 'test_mae': np.float64(27597675.68),
 'train_mae_ratio': np.float64(5.04),
 'test_mae_ratio': np.float64(13.18)}

단기, 학생, 년분기 삭제

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# 데이터프레임(df) 제공 필요
# 예: df = pd.read_csv('your_file.csv')

# '행정동'과 '업종별카테고리' 컬럼 원핫인코딩 수행
df2 = pd.get_dummies(df, columns=['행정동', '업종별카테고리'], drop_first=True)

# 피처와 타겟 설정
features = ['인구수', '지역생활인구', '장기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '버스정류장수'] + [col for col in df2.columns if col.startswith('행정동_') or col.startswith('업종별카테고리_')]
target = '월매출(점포)'

X = df2[features]
y = df2[target]

# 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 랜덤 포레스트 모델 학습 및 예측
model = RandomForestRegressor(random_state=42, n_jobs=-1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# 모델 평가 호출
evaluation_results5 = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)

# 결과 출력
evaluation_results5

{'Model': 'RandomForestRegressor',
 'Scaler': 'None',
 'train_mse': np.float64(681206546551264.6),
 'test_mse': np.float64(3670588506553207.5),
 'train_rmse': np.float64(26099933.84),
 'test_rmse': np.float64(60585381.95),
 'train_r2': 0.99,
 'test_r2': 0.95,
 'train_mae': np.float64(11072698.82),
 'test_mae': np.float64(28252353.33),
 'train_mae_ratio': np.float64(5.16),
 'test_mae_ratio': np.float64(13.49)}

단기, 학생, 인구

In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# 데이터프레임(df) 제공 필요
# 예: df = pd.read_csv('your_file.csv')

# '행정동'과 '업종별카테고리' 컬럼 원핫인코딩 수행
df2 = pd.get_dummies(df, columns=['행정동', '업종별카테고리'], drop_first=True)

# 피처와 타겟 설정
features = ['년분기', '지역생활인구', '장기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '버스정류장수'] + [col for col in df2.columns if col.startswith('행정동_') or col.startswith('업종별카테고리_')]
target = '월매출(점포)'

X = df2[features]
y = df2[target]

# 학습 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 랜덤 포레스트 모델 학습 및 예측
model = RandomForestRegressor(random_state=42, n_jobs=-1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# 모델 평가 호출
evaluation_results6 = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)

# 결과 출력
evaluation_results6

{'Model': 'RandomForestRegressor',
 'Scaler': 'None',
 'train_mse': np.float64(661279528221456.1),
 'test_mse': np.float64(3575916765507148.0),
 'train_rmse': np.float64(25715355.88),
 'test_rmse': np.float64(59798969.6),
 'train_r2': 0.99,
 'test_r2': 0.95,
 'train_mae': np.float64(10727298.62),
 'test_mae': np.float64(27512021.06),
 'train_mae_ratio': np.float64(5.0),
 'test_mae_ratio': np.float64(13.14)}

In [27]:
import pandas as pd

# 각 dict에 Del_Feature 추가
evaluation_results['Del_Feature'] = 'Default'
evaluation_results2['Del_Feature'] = '단기외국인'
evaluation_results3['Del_Feature'] = '학생수'
evaluation_results4['Del_Feature'] = '단기, 학생'
evaluation_results5['Del_Feature'] = '단기, 학생, 년분기'
evaluation_results6['Del_Feature'] = '단기, 학생, 인구수'

# 각 dict를 DataFrame으로 변환
all_results = [
    pd.DataFrame([evaluation_results]),
    pd.DataFrame([evaluation_results2]),
    pd.DataFrame([evaluation_results3]),
    pd.DataFrame([evaluation_results4]),
    pd.DataFrame([evaluation_results5]),
    pd.DataFrame([evaluation_results6]),
]

# 모든 DataFrame을 행 방향으로 병합
df_combined = pd.concat(all_results, ignore_index=True)

# 병합된 결과 확인
df_combined

,Model,Scaler,train_mse,test_mse,train_rmse,test_rmse,train_r2,test_r2,train_mae,test_mae,train_mae_ratio,test_mae_ratio,Del_Feature
0,RandomForestRegressor,None,6.807108e+14,3.912119e+15,26090435.92,62546938.10,0.99,0.95,11292838.94,29019445.18,5.26,13.85,Default
1,RandomForestRegressor,None,6.696083e+14,3.686518e+15,25876790.04,60716699.73,0.99,0.95,11015518.93,28199150.24,5.13,13.46,단기외국인
2,RandomForestRegressor,None,6.690455e+14,3.826396e+15,25865912.94,61857873.32,0.99,0.95,11102428.65,28524090.94,5.17,13.62,학생수
3,RandomForestRegressor,None,6.654477e+14,3.562207e+15,25796273.40,59684225.05,0.99,0.95,10811519.62,27597675.68,5.04,13.18,"단기, 학생"
4,RandomForestRegressor,None,6.812065e+14,3.670589e+15,26099933.84,60585381.95,0.99,0.95,11072698.82,28252353.33,5.16,13.49,"단기, 학생, 년분기"
5,RandomForestRegressor,None,6.612795e+14,3.575917e+15,25715355.88,59798969.60,0.99,0.95,10727298.62,27512021.06,5.00,13.14,"단기, 학생, 인구수"

In [28]:
df.columns

Index(['년분기', '행정동', '업종별카테고리', '월매출(점포)', '인구수', '지역생활인구', '장기외국인', '단기외국인',
       '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'],
      dtype='object')

In [ ]:
df.groupby(["년분기", "행정동", "업종별카테고리"])[""]