중복체크

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

In [20]:
df = pd.read_csv('source/no_open.csv')

In [21]:
jeju = df[df['MEET'] == '제주']
busan = df[df['MEET'] == '부산경남']

In [49]:
"""
filtered_df = jeju[jeju['ORD'].isin([1, 2, 3])]

grouped_df = filtered_df.groupby(['RC_DATE', 'RC_NO'])['ORD'].count().reset_index()

grouped_df[grouped_df['ORD'] >= 4]
"""

"\nfiltered_df = jeju[jeju['ORD'].isin([1, 2, 3])]\n\ngrouped_df = filtered_df.groupby(['RC_DATE', 'RC_NO'])['ORD'].count().reset_index()\n\ngrouped_df[grouped_df['ORD'] >= 4]\n"

In [28]:
busan['ORD'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
df_count = busan[busan['ORD'].isin([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])]

df_count2 = df_count.groupby(['RC_DATE', 'RC_NO', 'ORD'])['ORD'].count().reset_index(name = 'ORD_count')

df_count2

        RC_DATE  RC_NO  ORD  ORD_count
0      20190104      1    1          1
1      20190104      1    2          1
2      20190104      1    3          1
3      20190104      1    4          1
4      20190104      1    5          1
...         ...    ...  ...        ...
26423  20230702      7    6          1
26424  20230702      7    7          1
26425  20230702      7    8          1
26426  20230702      7    9          1
26427  20230702      7   10          1

[26428 rows x 4 columns]

In [32]:
df_count.columns

Index(['MEET', 'RC_DATE', 'RC_NO', 'RC_DIST', 'RANK', 'WEATHER', 'TR_CON',
       'TR_WC', 'ORD', 'CHUL_NO', 'HR_NAME', 'HR_NO', 'NAME', 'PRD_NAME',
       'AGE', 'SEX', 'horse_weight', 'weight_gain', 'RC_TIME', 'ORD1_CNT_T',
       'ORD2_CNT_T', 'RC_CNT_T', 'ORD1_CNT_Y', 'ORD2_CNT_Y', 'RC_CNT_Y',
       'WG_BUDAM', 'JK_NAME', 'JK_NO', 'JK_AGE', 'JK_CAREER', 'JK_ORD1_CNT_T',
       'JK_ORD2_CNT_T', 'JK_RC_CNT_T', 'JK_ORD1_CNT_Y', 'JK_ORD2_CNT_Y',
       'JK_RC_CNT_Y', 'TR_NAME', 'TR_NO', 'TR_AGE', 'TR_CAREER',
       'TR_ORD1_CNT_T', 'TR_ORD2_CNT_T', 'TR_RC_CNT_T', 'TR_ORD1_CNT_Y',
       'TR_ORD2_CNT_Y', 'TR_RC_CNT_Y', 'HR_ORD1_CNT_T', 'HR_ORD2_CNT_T',
       'HR_RC_CNT_T', 'SJ_S1F_ORD', 'SJ_1C_ORD', 'SJ_2C_ORD', 'SJ_3C_ORD',
       'SJ_G3F_ORD', 'SJ_4C_ORD', 'SJ_G1F_ORD', 'SE_S1F_ACC_TIME',
       'SE_1C_ACC_TIME', 'SE_2C_ACC_TIME', 'SE_3C_ACC_TIME', 'SE_G3F_ACC_TIME',
       'SE_4C_ACC_TIME', 'SE_G1F_ACC_TIME', 'JE_S1F_TIME', 'JE_1C_TIME',
       'JE_2C_TIME', 'JE_3C_TIME', 'JE_G3F_TIME', 'JE_4C_TIME', 'JE_G1F_TIME',
       'BU_S1F_ORD', 'BU_G8F_ORD', 'BU_G6F_ORD', 'BU_G4F_ORD', 'BU_G3F_ORD',
       'BU_G2F_ORD', 'BU_G1F_ORD', 'BU_S1F_TIME', 'BU_10-8F_TIME',
       'BU_8-6F_TIME', 'BU_6-4F_TIME', 'BU_4-2F_TIME', 'BU_2F-G_TIME',
       'BU_3F-G_TIME', 'BU_1F-G_TIME', 'BU_S1F_ACC_TIME', 'BU_G8F_ACC_TIME',
       'BU_G6F_ACC_TIME', 'BU_G4F_ACC_TIME', 'BU_G3F_ACC_TIME',
       'BU_G2F_ACC_TIME', 'BU_G1F_ACC_TIME'],
      dtype='object')

In [44]:
drop_duplicate = df_count.groupby(['RC_DATE', 'RC_NO', 'ORD', 'HR_NAME'])['MEET'].count()
drop_duplicate2 = drop_duplicate.reset_index()
len(drop_duplicate2[drop_duplicate2['MEET'] > 1].index)

487

In [43]:
df_count[['RC_DATE', 'RC_NO', 'ORD', 'HR_NAME']].shape

(26957, 4)

In [ ]:
# 드랍하고 남은 인덱스를 가져오기
index_to_select = df_count[['RC_DATE', 'RC_NO', 'ORD', 'HR_NAME']].drop_duplicates().index

In [ ]:
# 드랍하고 남은 인덱스를 이용해서 원본에서 행선택
df_count.loc[index_to_select, :]

,MEET,RC_DATE,RC_NO,RC_DIST,RANK,WEATHER,TR_CON,TR_WC,ORD,CHUL_NO,...,BU_2F-G_TIME,BU_3F-G_TIME,BU_1F-G_TIME,BU_S1F_ACC_TIME,BU_G8F_ACC_TIME,BU_G6F_ACC_TIME,BU_G4F_ACC_TIME,BU_G3F_ACC_TIME,BU_G2F_ACC_TIME,BU_G1F_ACC_TIME
28279,부산경남,20230702,1,1200,국6등급,맑음,다습,11,1,11,...,25.7,38.0,13.1,13.6,0.0,0.0,24.9,37.0,49.3,61.9
28280,부산경남,20230702,1,1200,국6등급,맑음,다습,11,2,10,...,26.5,38.5,13.9,13.5,0.0,0.0,24.4,36.6,48.6,61.2
28281,부산경남,20230702,1,1200,국6등급,맑음,다습,11,3,3,...,26.7,38.7,14.1,13.7,0.0,0.0,24.6,36.7,48.7,61.3
28282,부산경남,20230702,1,1200,국6등급,맑음,다습,11,4,5,...,26.0,38.4,13.5,13.9,0.0,0.0,25.1,37.3,49.7,62.2
28283,부산경남,20230702,1,1200,국6등급,맑음,다습,11,5,6,...,27.5,40.3,14.3,13.7,0.0,0.0,24.7,37.1,49.9,63.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55230,부산경남,20190104,13,1200,국3등급,맑음,건조,3,8,3,...,25.2,37.5,12.9,13.9,0.0,0.0,25.5,37.6,49.9,62.2
55231,부산경남,20190104,13,1200,국3등급,맑음,건조,3,9,10,...,25.7,37.9,13.3,14.0,0.0,0.0,25.5,37.2,49.4,61.8
55232,부산경남,20190104,13,1200,국3등급,맑음,건조,3,10,12,...,26.5,38.7,13.9,14.1,0.0,0.0,25.5,37.2,49.4,62.0
55233,부산경남,20190104,13,1200,국3등급,맑음,건조,3,11,6,...,26.2,38.5,13.7,14.1,0.0,0.0,25.6,37.9,50.2,62.7
55235,부산경남,20190104,13,1200,국3등급,맑음,건조,3,12,1,...,26.9,39.6,13.7,13.9,0.0,0.0,25.2,37.2,49.9,63.1

In [45]:
26957 - 26470

487

In [ ]:
df_count.drop_duplicates()

In [ ]:
df_count = busan[busan['ORD'].isin([1, 2, 3])]

df_count2 = df_count.groupby(['RC_DATE', 'RC_NO', 'ORD'])['ORD'].count().reset_index(name = 'ORD_count')

df_count2

np.int64(93)

In [15]:
# ORD 열의 중복 개수를 확인하여 추가하는 방식
df_duplicates = df.groupby(['RC_DATE', 'RC_NO'])['ORD'].nunique().reset_index()
df_duplicates.rename(columns={'ORD': 'unique_ORD_count'}, inplace=True)

# 중복이 있는 그룹만 필터링하기
df_duplicates[df_duplicates['unique_ORD_count'] > 1]

       RC_DATE  RC_NO  unique_ORD_count
0     20190104      1                12
1     20190104      2                12
2     20190104      3                12
3     20190104      4                12
4     20190104      5                11
...        ...    ...               ...
4619  20230702      3                11
4620  20230702      4                11
4621  20230702      5                10
4622  20230702      6                 9
4623  20230702      7                10

[4595 rows x 3 columns]

In [ ]:
df[(df['MEET'] == '부산경남') & (df['RC_DATE'] == 20190104) & (df['RC_NO'] == 11)]

,MEET,RC_DATE,RC_NO,RC_DIST,RANK,WEATHER,TR_CON,TR_WC,ORD,CHUL_NO,...,BU_2F-G_TIME,BU_3F-G_TIME,BU_1F-G_TIME,BU_S1F_ACC_TIME,BU_G8F_ACC_TIME,BU_G6F_ACC_TIME,BU_G4F_ACC_TIME,BU_G3F_ACC_TIME,BU_G2F_ACC_TIME,BU_G1F_ACC_TIME
63253,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,1,7,...,26.4,38.9,13.7,14.3,0.0,25.7,49.9,62.5,75.0,87.7
63254,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,2,10,...,26.3,38.8,13.5,14.6,0.0,26.3,50.3,62.8,75.3,88.1
63255,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,3,4,...,26.3,38.9,13.5,14.2,0.0,25.7,50.1,62.8,75.4,88.2
63256,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,4,11,...,27.0,39.8,13.9,14.0,0.0,25.2,49.4,61.9,74.7,87.8
63257,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,5,6,...,26.2,38.6,13.5,15.1,0.0,27.0,50.5,63.2,75.6,88.3
63258,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,6,9,...,27.0,39.8,14.0,14.2,0.0,25.4,49.5,62.1,74.9,87.9
63259,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,7,2,...,27.5,40.0,14.4,14.9,0.0,26.4,50.2,62.8,75.3,88.4
63260,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,7,2,...,27.5,40.0,14.4,14.9,0.0,26.4,50.2,62.8,75.3,88.4
63261,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,8,3,...,27.2,40.3,14.0,14.2,0.0,25.6,50.3,63.5,76.6,89.8
63262,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,9,8,...,29.3,42.3,15.3,14.0,0.0,25.1,49.3,61.9,74.9,88.9
63263,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,10,1,...,27.9,41.6,14.4,14.2,0.0,25.6,50.9,64.4,78.1,91.6
63264,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,11,5,...,30.4,44.0,15.8,13.9,0.0,25.1,49.3,62.0,75.6,90.2
63265,부산경남,20190104,11,1600,혼4등급,흐림,건조,3,12,12,...,31.6,45.0,17.1,14.9,0.0,26.4,50.4,63.4,76.8,91.3

In [ ]:
temp_df2 = temp_df.groupby(['MEET', 'RC_DATE', 'RC_NO'])['ORD'].max().reset_index()

In [ ]:
(temp_df2['ORD'] >= 90).sum()

np.int64(0)

In [ ]:
temp_df2.groupby('ORD')['MEET'].count()

ORD
6        9
7       74
8      349
9      618
10    2291
11     661
12    1419
13      76
14     281
15       3
16      10
Name: MEET, dtype: int64

In [ ]:
df[(df['RC_DATE'] == 20230616) & (df['RC_NO'] == 2)]

,MEET,RC_DATE,RC_NO,RC_DIST,RANK,WEATHER,TR_CON,TR_WC,ORD,CHUL_NO,...,BU_2F-G_TIME,BU_3F-G_TIME,BU_1F-G_TIME,BU_S1F_ACC_TIME,BU_G8F_ACC_TIME,BU_G6F_ACC_TIME,BU_G4F_ACC_TIME,BU_G3F_ACC_TIME,BU_G2F_ACC_TIME,BU_G1F_ACC_TIME
390,제주,20230616,2,800,제6등급,맑음,건조,4,1,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
391,제주,20230616,2,800,제6등급,맑음,건조,4,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
392,제주,20230616,2,800,제6등급,맑음,건조,4,3,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
393,제주,20230616,2,800,제6등급,맑음,건조,4,4,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
394,제주,20230616,2,800,제6등급,맑음,건조,4,5,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
395,제주,20230616,2,800,제6등급,맑음,건조,4,6,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
396,제주,20230616,2,800,제6등급,맑음,건조,4,7,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
397,제주,20230616,2,800,제6등급,맑음,건조,4,8,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
398,제주,20230616,2,800,제6등급,맑음,건조,4,9,10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
399,제주,20230616,2,800,제6등급,맑음,건조,4,94,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29983,부산경남,20230616,2,1200,국6등급,맑음,건조,4,1,4,...,25.3,37.3,13.3,14.0,0.0,0.0,25.6,37.9,49.9,61.9
29984,부산경남,20230616,2,1200,국6등급,맑음,건조,4,2,1,...,26.0,37.9,13.6,14.0,0.0,0.0,25.6,37.9,49.8,62.2
29985,부산경남,20230616,2,1200,국6등급,맑음,건조,4,3,3,...,26.5,38.7,14.1,14.0,0.0,0.0,25.5,37.7,49.9,62.3
29986,부산경남,20230616,2,1200,국6등급,맑음,건조,4,4,8,...,26.2,38.6,13.6,14.1,0.0,0.0,25.7,38.1,50.5,63.1
29987,부산경남,20230616,2,1200,국6등급,맑음,건조,4,5,5,...,26.5,38.8,13.8,14.0,0.0,0.0,25.7,38.2,50.5,63.2
29988,부산경남,20230616,2,1200,국6등급,맑음,건조,4,6,6,...,26.3,38.8,13.6,14.1,0.0,0.0,26.1,38.7,51.2,63.9
29989,부산경남,20230616,2,1200,국6등급,맑음,건조,4,7,9,...,25.9,38.4,13.5,14.4,0.0,0.0,26.5,39.3,51.8,64.2
29990,부산경남,20230616,2,1200,국6등급,맑음,건조,4,8,7,...,26.6,39.2,13.8,14.2,0.0,0.0,26.1,38.7,51.3,64.1
29991,부산경남,20230616,2,1200,국6등급,맑음,건조,4,9,10,...,26.8,39.1,14.0,14.6,0.0,0.0,26.4,39.0,51.3,64.1
29992,부산경남,20230616,2,1200,국6등급,맑음,건조,4,10,2,...,28.9,41.8,15.3,14.3,0.0,0.0,26.1,38.9,51.8,65.4

In [ ]:
df.groupby(['ORD'])['RC_NO'].count()
df[df['ORD'] >= 90]

,MEET,RC_DATE,RC_NO,RC_DIST,RANK,WEATHER,TR_CON,TR_WC,ORD,CHUL_NO,...,BU_2F-G_TIME,BU_3F-G_TIME,BU_1F-G_TIME,BU_S1F_ACC_TIME,BU_G8F_ACC_TIME,BU_G6F_ACC_TIME,BU_G4F_ACC_TIME,BU_G3F_ACC_TIME,BU_G2F_ACC_TIME,BU_G1F_ACC_TIME
399,제주,20230616,2,800,제6등급,맑음,건조,4,94,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
689,제주,20230602,1,800,제6등급,안개,포화,18,99,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
690,제주,20230602,1,800,제6등급,안개,포화,18,99,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
691,제주,20230602,1,800,제6등급,안개,포화,18,99,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
692,제주,20230602,1,800,제6등급,안개,포화,18,99,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62997,부산경남,20190111,2,1300,국6등급,맑음,건조,3,94,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63055,부산경남,20190111,8,1300,국5등급,맑음,건조,3,95,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63170,부산경남,20190104,2,1000,국6등급,맑음,건조,3,95,10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63182,부산경남,20190104,3,1000,국6등급,맑음,건조,3,94,12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63279,부산경남,20190104,12,1800,1등급,흐림,건조,3,92,12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
print( temp_df['ORD'].min() )

df[df['ORD'] < 7]

6

,MEET,RC_DATE,RC_NO,RC_DIST,RANK,WEATHER,TR_CON,TR_WC,ORD,CHUL_NO,...,BU_2F-G_TIME,BU_3F-G_TIME,BU_1F-G_TIME,BU_S1F_ACC_TIME,BU_G8F_ACC_TIME,BU_G6F_ACC_TIME,BU_G4F_ACC_TIME,BU_G3F_ACC_TIME,BU_G2F_ACC_TIME,BU_G1F_ACC_TIME
0,제주,20230701,1,800,제6등급,흐림,포화,18,1,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,제주,20230701,1,800,제6등급,흐림,포화,18,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,제주,20230701,1,800,제6등급,흐림,포화,18,3,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,제주,20230701,1,800,제6등급,흐림,포화,18,4,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,제주,20230701,1,800,제6등급,흐림,포화,18,5,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61838,부산경남,20190104,13,1200,국3등급,맑음,건조,3,2,11,...,25.7,37.5,13.4,13.6,0.0,0.0,24.8,36.5,48.3,60.6
61839,부산경남,20190104,13,1200,국3등급,맑음,건조,3,3,7,...,25.6,37.6,13.2,14.1,0.0,0.0,25.2,36.8,48.8,61.2
61840,부산경남,20190104,13,1200,국3등급,맑음,건조,3,4,2,...,25.0,37.1,12.9,13.8,0.0,0.0,25.3,37.3,49.4,61.5
61841,부산경남,20190104,13,1200,국3등급,맑음,건조,3,5,8,...,26.4,38.6,13.7,13.6,0.0,0.0,24.7,36.4,48.6,61.3
61842,부산경남,20190104,13,1200,국3등급,맑음,건조,3,6,9,...,26.4,38.5,13.7,13.8,0.0,0.0,25.0,36.6,48.7,61.4

In [ ]:
df.groupby('ORD')['MEET'].count()

ORD
1     5820
2     5820
3     5820
4     5824
5     5828
6     5846
7     5850
8     5771
9     5409
10    4808
11    2511
12    1835
13     381
14     304
15      13
16      10
Name: MEET, dtype: int64